Repository clouddrove/terraform-aws-cloudwatch-dashboard, pull requests merged in 2023-11, with the labels that each got.

#6 feat: cloudwatch dashboard resource with example
  .github/workflows/readme.yml
  _example/complete/lambda_dashboard.json
  _example/complete/lambda_packages/index.py
  _example/complete/main.tf
  _example/complete/test-dashboard-lambda-function.zip
  _example/complete/versions.tf
  main.tf
  outputs.tf
  variables.tf
  versions.tf
Labels: enhancement, Work In Progress

#7 Feat: 🚀 Add example for ECR Cloudwatch dashboard
  .deepsource.toml
  .gitignore
  .releaserc.json
  Makefile
  README.yaml
  _example/complete/main.tf
  _example/complete/output.tf
  _example/complete/versions.tf
  _example/ecr_dashboard/ecr_dashboard.json
  _example/ecr_dashboard/main.tf
  _example/ecr_dashboard/output.tf
  _test/complete/watch_test.go
  outputs.tf
  versions.tf
Labels: enhancement

#8 Fix: Fix readme check
  .deepsource.toml
  Makefile
  README.md
Labels: bug
